### ISSUE TITLE
Email didn't fill into SMF

### ISSUE THREAD

**Issue by NewCoCo** [xchwarze/WP2SMFBridge#1]
Hi email didn't apear into SMF after registering in WorpPress, but the user is created.

WordPress last version and SMF last 2.0.9 stable version. TapTalk plugin is installed

is it possible, when changing email into WordPress it's chaning into SMF as well as a password?

as well as if changing the apered Name will be awesome too (so I may disable all options into SMF like changing email, password, apeearing name on the Forum and do those changes into WP only)

**Comment by xchwarze** [comment]
change on bridge.php the line 235:
'email_address' => "'" . addslashes($user_email) . "'",
to
'email_address' => "'" . addslashes($email_address) . "'",

or upgrade to last commit
