### ISSUE TITLE
Works fine locally, but not on web host

### ISSUE THREAD

**Issue by Luthien-in-edhil** [xchwarze/WP2SMFBridge#5]
Hello,

I installed this plugin on a local copy of a Wordpress (4.4) site. It has SMF (2.0.11) installed in a `/forum` subfolder within the Wordpress site.
The local instance runs under MAMP on a mac (Apache, MySQL) and it works great. 

But I cannot get it to work on the web host. It has the exact same versions of WP and SMF, and also uses MySQL. I configured the WP2SMFBridge plugin on Wordpress to point to the `forum/` directory, as I did locally. I also disabled the cookie settings as you specified.
I also checked the file permissions on the host: for the SMF Settings.php: they are 755, so that should be readable by the plugin. 

But whatever I try, it does not work there. It's too bad that I don't have a proper PHP log there but I'll ask the provider if they can give that. 

Do you have any idea what else I could look into? 

Thanks in advance!

**Comment by Luthien-in-edhil** [comment]
There seem to be a couple of things off: 
In bridge.php, function smfURLParts, line 160, there's this return statement: 

``` php
return array($parsed_url['host'], $parsed_url['path'] . '/');
```

which returns an indexed array of two strings. However, the calling function smfSetLoginCookie expects key => value pairs: 

``` php
(...) $parsed_url['path'] . '/', $parsed_url['host'], 0);
```

Also, you can see from the above that there are two slashed added altogether to the value of 'path' - at least, if it would be read :)

Another issue was that in both `smfSetLoginCookie` and `smfLogoutByMember` the `smfURLParts` returned empty strings anyhow because these `false` were passed in: 

``` php
$localCookies = false;
$globalCookies = false;
```

Altogether, I made these changes, after which it works: 
line 131/2 & 164/5: changed false to true

``` php
$localCookies = true;
$globalCookies = true;  
```

in function smfURLParts() (~ line 153), changed

``` php
$parsed_url['host'] = '.' . $parts[1]; 
```

into

``` php
$parsed_url['host'] = $parts[1];
```

because it only prefixed the hostname with a period (though it did no harm, either)
~ line 159: changed the return statement from

``` php
return array($parsed_url['host'], $parsed_url['path'] . '/');
```

to, simply:

``` php
return $parsed_url;
```

... which also does away with the double slash. 

Like this the code works fine on our server, though I understand that it should actually also create users in SMF that don't yet exist. Well, it doesn't - I need to have the users exist in WP AND SMF, and then it works. But that's fine in our case. 

Note to possible other users looking for a fix: this is kind of a hack, I do this on my own responsibility. For one thing, It might be that I unknowingly did something illegal with the cookies - they're practically politically incorrect by now :) - but seriously, it's just a hack. I hope that there will come a solid fix! I'll leave the issue open, because it's not fixed by this.

**Comment by ejohann** [comment]
I am also having issues.  Works well for admin user, but no new user registered through wordpress is added to smf.  Any assistance appreciated.  I can send link to my website. Thanks

**Comment by xchwarze** [comment]
i rewrite all code for v2, test with this version
