### ISSUE TITLE
SMF 2.0.16+ Cookie issue

### ISSUE THREAD

**Issue by VBGAMER45** [xchwarze/WP2SMFBridge#6]
SMF has made an update to how cookies are handled

https://www.simplemachines.org/community/index.php?topic=570989.0

> require_once($sourcedir . '/Load.php');

// Use strong cookie
if (function_exists('get_auth_secret'))

	

$hashed_password = hash_hmac('sha1', sha1($user_info['passwd'] . $user_info['password_salt']), get_auth_secret());
// Fallback for older versions
else

	

$hashed_password = sha1($user_info['passwd'] . $user_info['password_salt']);

**Comment by xchwarze** [comment]
Hi!
Please add this via pull request

**Comment by VBGAMER45** [comment]
Thanks for reply. Added when you get a chance and if it checks out update wordpress.org they have 2.0.0 still on the site.
